version: '3.7'

services:
  springproject:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080" # 8082포트로 외부 접속 8082 -> 8080-> spring으로 연결
    container_name: springproject